security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: ghtdK7, roles: 'ROLE_ADMIN' }
                    user: { password: ferus5, roles: 'ROLE_VIEW' }

    role_hierarchy:
            ROLE_ADMIN:       ROLE_VIEW

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login: ~
            logout: ~

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/admin, roles: ROLE_VIEW }