home:
    path:     /
    defaults: { _controller: FerusYearBookBundle:Public:index }

request_pass:
    path:     /request-pass/{id}
    defaults: { _controller: FerusYearBookBundle:Public:requestPass }

admin:
    path:     /admin
    defaults: { _controller: FerusYearBookBundle:Public:admin }

export_photos:
    path:     /admin/export
    defaults: { _controller: FerusYearBookBundle:Public:exportPhoto }

show:
    path:     /admin/{id}
    defaults: { _controller: FerusYearBookBundle:Public:show }

thumb:
    path:     /thumb/{id}
    defaults: { _controller: FerusYearBookBundle:Public:thumb }

reminder:
   path:     /admin/reminder/{page}
   defaults: { _controller: FerusYearBookBundle:Public:sendReminder }

api_get_student:
    path:   /search/{query}
    defaults: { _controller: FerusYearBookBundle:Public:search }
