<?php

namespace Ferus\YearBookBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function querySearch($query)
    {
        $qb = $this->createQueryBuilder('s');
        if($query == null) return $qb->getQuery();
        $query = trim($query);
        $words = explode(' ', $query);
        if(count($words) === 1){
            if(preg_match('/^[0-9]+$/', $query))
                $qb
                    ->where('s.id = :id')
                    ->setParameter('id', $query);
            else
                $qb
                    ->where('s.firstName LIKE :query')
                    ->orWhere('s.lastName LIKE :query')
                    ->setParameter('query', "%$query%");
        }
        else{
            foreach($words as $key => $word){
                $qb
                    ->andWhere("s.firstName LIKE :query$key OR s.lastName LIKE :query$key")
                    ->setParameter("query$key", "%$word%");
            }
        }
        return $qb->getQuery();
    }

    public function search($query)
    {
        $q = $this->querySearch($query);
        try{
            $student = $q->getSingleResult(Query::HYDRATE_ARRAY);
        }
        catch(\Exception $e){
            return null;
        }

        if(isset($student['firstName'])) $student['first_name'] = $student['firstName'];
        if(isset($student['lastName'])) $student['last_name'] = $student['lastName'];

        return $student;
    }

    public function findAsArray($id)
    {
        try{
            $student = $this->createQueryBuilder('s')
                ->where('s.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleResult(Query::HYDRATE_ARRAY);
        }
        catch(NoResultException $e){
            return null;
        }

        if(isset($student['firstName'])) $student['first_name'] = $student['firstName'];
        if(isset($student['lastName'])) $student['last_name'] = $student['lastName'];
        $student['password'] = sha1(uniqid());

        return $student;
    }
}
